version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  servicewidgetdemo:
    build:
      context: .
    dns: 8.8.8.8
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/kb/module
    # no environment needed as all services are mocked locally